### ISSUE TITLE
how to migrate from v4 to v5

### ISSUE THREAD

**Issue by darkworks** [austinksmith/Hamsters.js#56]
### New Issue Report

* ***What version of the library are you using?***

am using v4.1.2 its working i was thinking to update it to v5 i have downloaded v5 and replaced v4 files with it . but am getting error 

`Uncaught TypeError: _hamsters2.default.init is not a function`
am using webpack 4 environment 

i imported it like 
`import hamsters from './../../../node_modules/hamsters.js/build/hamsters.js';`
the i have starting params 
```
			// init hamster
		  var startOptions = {
			maxThreads: navigator.hardwareConcurrency,
			cache: false,
			debug: true,
			persistence: false
		};  
			hamsters.init(startOptions);
```

so wondering what need to be change for v5 , i go through wiki its installation it shows hamsters.init

* ***What operating system are you seeing the issue on?***

windows 7 

* ***Which platform (and or) browser are you seeing the issue on?***

vanilla js , webpack 4.1

* ***What is the version of the platform (and or) browser you are seeing the issue on?***

chrome v70

**Comment by austinksmith** [comment]
Try changing your import to this path...

```build/hamsters.web.min.js```

**Comment by austinksmith** [comment]
Take a look at the build folder, there are now two different versions of the library ... one for web and one for node https://github.com/austinksmith/Hamsters.js/tree/v5.1.1/build

**Comment by darkworks** [comment]
ya i understand the point , however i have already changed file name from hamsters.web.min.js  to hamsters.js  as it was in old so that i have not to change files names every where , webpack have build it too but still getting error, am calling  hamsters.init(startOptions);  inside constructor

**Comment by austinksmith** [comment]
Hmm, try to not change the file name, the .map file might cause some problems and web pack probably doesn't like that the file name is changed. I'm getting my environment setup for react native debugging right now, if ```hamsters.init``` is undefined then it's likely you just need to wipe out the hamsters.js file and reinstall again and then make sure you reference it using the proper file name instead of renaming it. If the .web.min.js file doesn't work, then give the .node.min.js file a try. One of them should work

**Comment by darkworks** [comment]
ok thanks 
![image](https://user-images.githubusercontent.com/12841788/49159999-9900e380-f347-11e8-8421-555fb1b3782a.png)

i changed files names to default  hamsters.web.min.js now error changed to 

`TypeError: _hamstersWebMin2.default.init is not a function`

**Comment by darkworks** [comment]
oh you were right 

used hamsters.node.min.js  it worked 

but there is path problem its looking for file it wrong place 
giving error 
`http://localhost/script/common/rnHamstersWheel.js 404 (Not Found)`
although its near to it in its folder but its looking outside the node_modules folder

**Comment by austinksmith** [comment]
Try overriding the init call like this...


```js

hamsters.init({
   reactNative: false
});

```

**Comment by darkworks** [comment]
i did disable reactnative after that it generate few new errors 
```
GET http://localhost/job/home/continuity/public_html/gerberviewer_mod/gpro/gvie…rams.hamstersJob)(),rtn.threadEnd=Date.now(),postMessage(e(rtn),r(rtn))})} 403 (Forbidden) hamsters.node.min.js:1 
Hamsters.js v5.1.1 Error: #undefined in undefined: undefined @ 1543422721232
Hamsters.js v5.1.1 Error: undefined @ 1543422721233
```

**Comment by austinksmith** [comment]
Are you using v5.1.1?

**Comment by darkworks** [comment]
ya

**Comment by austinksmith** [comment]
I think I would need to see your specific application to be able to debug what exactly is returning undefined, it looks like you're trying to access a variable within a thread that doesn't exist? If you can email me the repo in question or files I can take a closer look - austin@asmithdev.com

**Comment by darkworks** [comment]
hmmmm ok i will mail you code block which is trigger it , probably tomorrow as its late night here , however my application is working ok with v4.2 smooth no issue , update reason was that maybe debugger have improved in v5 as some time i have hard time in finding line# on which error occur inside hamster block . 

thanks for the amazing work and assistance :)

**Comment by darkworks** [comment]
so i write this simple test function to test and its giving same error on it too 

```
	async testhamster(){
		console.log('heloo world test');
				var thread_init = 1;
				var thread_comp = 0;				
				var params = {
					teststr: "hellooo",
					};			
			hamsters.run(params, function() {
				var teststr = params.teststr;	
				console.log(teststr);
				teststr = "world";
				rtn.data.push([teststr]);	
				
			}, function(ctdata) {
			thread_comp++;	
			console.log(ctdata);
		}.bind(this));
		while(1){
          	if(thread_comp === thread_init){
				break;
			}
		//	console.log('wait');
			await this.sleep(50);	
		}			
	}
```

so when i call it 

![image](https://user-images.githubusercontent.com/12841788/49202481-8da0cd00-f3c6-11e8-83d6-ce49e8f4634c.png)

**Comment by darkworks** [comment]
i have sent mail , i created test app , please review 

thanks

**Comment by austinksmith** [comment]
So I tried running your app, I can get it to compile and I can get it to spin up the server on localhost:8080 but it's only serving as a file directory and not a webserver

**Comment by austinksmith** [comment]
So evidently you just need to initialize the library without passing the start options...

For some reason when you are passing ``` persistence: false ``` the library is breaking, so just keep persistence mode on and you shouldn't have the problem anymore. 

I'll try to figure out whats going on with the web and non persistence mode with the next release, for now though you'll probably get better performance without disabling persistence mode

**Comment by austinksmith** [comment]
Tested with v5.0.0 and v5.1.1., both work with your example app if you don't disable persistence which is on by default

**Comment by austinksmith** [comment]
Last note, I also see that you were manually setting maxThreads to navigator.hardwareConcurrency but the library does that for you automatically so you don't need to do that
